version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: api_backend
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
      - /app/node_modules

  client:
    build:
      context: ./frontend
    container_name: client_frontend
    ports:
      - '8000:8000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
